<div id="confirmmodal" class="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog modal-body">
        
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="formtitle">Confirm<span id="user"></span></h4>
        </div>
        <div class="modal-body">
            <div class="alert alert-info" role="alert">
                
                <span id="description"></span>
              </div>
            <div id="progress"><center></center></div>
            
            
            <div>
                <input name="itemid" value="" type="hidden" />
                <input name="periodid" value="" type="hidden" />
            </div>
        </div>
       <div class="modal-footer">
           <button name="btnSave" value="1" id="btngenerate" class="btn btn-primary ">&nbsp;Start</button>
           <button type="button" id="btncancel" class="btn btn-warning" data-dismiss="modal">Cancel</button>
           
      </div>
    </div>
  </div> 
</div>