<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2FileUpload\Module'                      => __DIR__ . '/Module.php',
    'ZF2FileUpload\Controller\Examples'         => __DIR__ . '/src/ZF2FileUpload/Controller/Examples.php',
    'ZF2FileUpload\Controller\PrgExamples'      => __DIR__ . '/src/ZF2FileUpload/Controller/PrgExamples.php',
    'ZF2FileUpload\Controller\ProgressExamples' => __DIR__ . '/src/ZF2FileUpload/Controller/ProgressExamples.php',
    'ZF2FileUpload\Form\CollectionUpload'       => __DIR__ . '/src/ZF2FileUpload/Form/CollectionUpload.php',
    'ZF2FileUpload\Form\FieldsetUpload'         => __DIR__ . '/src/ZF2FileUpload/Form/FieldsetUpload.php',
    'ZF2FileUpload\Form\MultiHtml5Upload'       => __DIR__ . '/src/ZF2FileUpload/Form/MultiHtml5Upload.php',
    'ZF2FileUpload\Form\ProgressUpload'         => __DIR__ . '/src/ZF2FileUpload/Form/ProgressUpload.php',
    'ZF2FileUpload\Form\SingleUpload'           => __DIR__ . '/src/ZF2FileUpload/Form/SingleUpload.php',
);