<div class="col col-md-2 alert-info">
        <h3><i class="glyphicon glyphicon-globe"></i> Quick Access</h3> 
        <hr>
        <ul class="nav nav-pills nav-stacked nav-wrap">
            <li role="presentation"><a href="<?php echo $this->url("administration",array("action"=>"index")); ?>"><i class="glyphicon glyphicon-user"></i> User Management</a></li>
            <li role="presentation"><a href="<?php echo $this->url("administration",array("action"=>"departments")); ?>"><i class="glyphicon glyphicon-calendar"></i> Departments</a></li>
            <li role="presentation"><a href="<?php echo $this->url("administration",array("action"=>"programs")); ?>"><i class="glyphicon glyphicon-stats"></i> Programmes </a></li>
            <li role="presentation"><a href="<?php echo $this->url("administration",array("action"=>"modules")); ?>"><i class="glyphicon glyphicon-question-sign"></i> Modules</a></li>
            <li role="presentation"><a href="#allocation" data-toggle="collapse" data-parent="#allocation"><i class="glyphicon glyphicon-thumbs-up"></i> Allocations</a></li>
            <div class="collapse" id="allocation">
                <a href="<?php echo $this->url("administration",array("action"=>"departments")); ?>" class="list-group-item">Lecturer</a>
                <a href="<?php echo $this->url("administration",array("action"=>"classes")); ?>" class="list-group-item">Module allocation</a>
            </div> 
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-user"></i> Faculty</a></li>

        </ul>
        <hr>
</div>