<div class="col col-md-2 alert-info">
        <h3><i class="glyphicon glyphicon-globe"></i> Quick Access</h3> 
        <hr>
        <ul class="nav nav-pills nav-stacked nav-wrap">
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-user"></i> User Management</a></li>
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-calendar"></i> Departments</a></li>
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-stats"></i> Programmes </a></li>
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-road"></i> Classes</a></li>
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-question-sign"></i> Courses</a></li>
            <li role="presentation"><a href="#"><i class="glyphicon glyphicon-user"></i> Faculty</a></li>

        </ul>
        <hr>
</div>