<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Hostel details</h4>
                    <div class="panel-body">
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $name = (!empty($details))?$details->getHostelName():$form->get('Hostel')->get('hostelName')->getValue();
    $campus = (!empty($details))?$details->getFkCampusid():$form->get('Hostel')->get('fkCampusid')->getValue();
    $category = (!empty($details))?$details->getFkHtid():$form->get('Hostel')->get('fkHtid')->getValue();
    $id   = (!empty($details))?$details->getPkHostelid():$form->get('Hostel')->get('pkHostelid')->getValue();
 ?>
                            
    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Hostel')->get('hostelName')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Hostel')->get('hostelName')->setValue($name)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Hostel')->get('hostelName')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Hostel')->get('fkCampusid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Hostel')->get('fkCampusid')->setValue($campus)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Hostel')->get('fkCampusid')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Hostel')->get('fkHtid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Hostel')->get('fkHtid')->setValue($category)); ?>
           <?php echo $this->formHidden($form->get('Hostel')->get('pkHostelid')->setValue($id)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Hostel')->get('fkHtid')); ?></div>
    </div>
                            

    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("accommodation",array("action"=>"index")); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>