<div class="row">
<div class="col col-md-1">
    &nbsp;
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> </h3>
            <div class="panel-body">
                <a href="<?php echo $this->url("examination",array("action"=>"mam")); ?>" class="btn btn-sm btn-warning "><i class="glyphicon glyphicon-arrow-left"></i> Return </a>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"assessmentitemform","id"=>$module->getPkClassmoduleid())); ?>" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-plus"></i> Create </a> <a href="<?php echo $this->url("examination",array("action"=>"amrk","id"=>$module->getPkClassmoduleid())); ?>" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-check"></i> Aggregate </a> <br>
            <hr>
            <blockquote class="panel-primary"><?php echo sprintf("%s (%s)",$module->getFkModuleid()->getModuleName(),$module->getFkModuleid()->getModuleCode()); ?> assessment items</blockquote>
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>type</th>
        <th>Weighting(%)</th>
        <th>Date created</th>
        <th width="170">Grades captured(%)</th>
        <th width="180"></th>
      </tr>
    </thead>
    <tbody>
      <?php
     
      foreach($items as $item){
          $percentage = round(($marks[$item->getPkAiid()]/count($students)) * 100);
          if($percentage >= 100){
              $status = "progress-bar-success";
          }elseif($percentage < 50){
              $status = "progress-bar-danger";
          }else{
              $status = "progress-bar-warning";
          }
      ?>

      <tr>
          <td><?php echo $item->getAssessmentTitle(); ?></td>
        <td><?php echo $item->getFkAtid()->getTypeName(); ?></td>
        <td><?php echo $item->getWeighting(); ?></td>
        <td><?php echo date_format($item->getCreatedon(), "d M Y"); ?></td>
        <td align="right">
            <div class="progress">
                    <div class="progress-bar <?php echo $status; ?> progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                         aria-valuemax="100" style="width: <?php echo $percentage; //$marks[$item->getPkAiid()]; ?>%;">
                        <?php echo $percentage; //$marks[$item->getPkAiid()]; ?>%
                    </div>
                </div>
        <td>
            <a href="<?php echo $this->url("examination",array("action"=>"assessmentitemform","id"=>$module->getFkModuleid()->getPkModuleid(),"subparam"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?php echo $this->url("examination",array("action"=>"asq","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-question-sign"></i></a>
            <a href="<?php echo $this->url("examination",array("action"=>"cam","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-import"></i></a>
            <a href="<?php echo $this->url("examination",array("action"=>"assessements")); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>    </td>
      </tr>
      
      <?php
      //$rate = (2 * $rate) + 20;
      }
      
      ?>
    </tbody>
</table>
           
            </div>
                </div>
        </div>
</div>
        