<div class="row">
<div class="col col-md-2">
    &nbsp;
    </div>
        <div class="col col-md-8">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s (%s)",$item->getAssessmentTitle(),$item->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?> - capture marks</h3>
         <?php
    $form->setAttributes(array('autocomplete'=>'off','id'=>'frmapplication'))->prepare();
    echo $this->form()->openTag($form); 
    ?>   
         <div class="panel-body">
                
             &nbsp;<a href="<?php echo $this->url("examination",array("action"=>"im","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-success pull-right"><i class="glyphicon glyphicon-upload"></i> Import marks </a>&nbsp;<button type="submit" class="btn btn-sm btn-success" name="save"><i class="glyphicon glyphicon-save"></i> Save </button>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"asmnts","id"=>$item->getFkClassmoduleid()->getPkClassmoduleid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-remove"></i> Cancel </a>
            <hr>
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
          <th></th>
          <?php
          if($item->getFkAtid()->getTypeCode()=="EXAM"){
          ?>
         <th>Examination #</th>
         <?php
          }elseif($item->getFkAtid()->getTypeCode()=="ASS" || $item->getFkAtid()->getTypeCode()=="MID"){
         ?>
        <th>Registration #</th>
        <th>Surname</th>
        <th>First name</th>
        <th>Gender</th>
        <?php
        }
        ?>
        <th width="100">Mark</th>
      </tr>
    </thead>
    <tbody>
        <input name="fkStaffid" type="hidden" value="<?php echo $item->getFkStaffid()->getPkStaffid(); ?>" />
        <input name="fkAiid" type="hidden" value="<?php echo $item->getPkAiid(); ?>" />
      <?php
      $counter = 1;
      foreach($form->get('mark')->getIterator() as $studentid=>$markfield){
          
          $mark     = (!empty($marks[$students[$studentid]['STUDENTCLASSID']]['mark']))?$marks[$students[$studentid]['STUDENTCLASSID']]['mark']:'';
          $id        = (!empty($marks[$students[$studentid]['STUDENTCLASSID']]['id']))?$marks[$students[$studentid]['STUDENTCLASSID']]['id']:'';
      ?>

      <tr>
          <td><?php echo $counter; ?></td>
          <input name="student[<?php echo $studentid; ?>]" type="hidden" value="<?php echo $students[$studentid]['STUDENTCLASSID']; ?>" />
          <input name="pkSmid[<?php echo $studentid; ?>]" type="hidden" value="<?php echo $id; ?>" />
          <?php
          if($item->getFkAtid()->getTypeCode()=="EXAM"){
          ?>
          <td><?php echo $students[$studentid]['EXAMNUMBER']; ?></td>
          <?php
          }elseif($item->getFkAtid()->getTypeCode()=="ASS" || $item->getFkAtid()->getTypeCode()=="MID"){
         ?>
          
          <td><?php echo $students[$studentid]['REGNUMBER']; ?></td>
          <td><?php echo $students[$studentid]['SURNAME']; ?></td>
        <td><?php echo $students[$studentid]['FIRSTNAME']; ?></td>
        <td><?php echo $students[$studentid]['GENDER']; ?></td>
         <?php
        }
        ?>
        <td><?php  echo $this->formElement($markfield->get('mark')->setValue($mark)); ?></td>
      </tr>
      
      <?php
      $counter++;
      }
      
      ?>
    </tbody>
</table>
       <hr>
       <button type="submit" class="btn btn-sm btn-success" name="save"><i class="glyphicon glyphicon-save"></i> Save </button>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"asmnts","id"=>$item->getFkClassmoduleid()->getPkClassmoduleid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-remove"></i> Cancel </a>
            </div>
            <?php
            echo $this->form()->closeTag();
            ?>
                </div>
        </div>
</div>
        