<?php
echo $this->partial('include/form/confirm.phtml');
echo $this->partial('include/form/modalform.phtml');
//echo $this->partial('include/form/importassessment.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
     $("a[title='modify']").click(function(){
        $("input[name='groupCode']").val($("#code"+this.id).html());
        $("input[name='groupName']").val($("#name"+this.id).html());
        $("input[name='level']").val($("#level"+this.id).html());
        $("input[name='pkGroupid']").val($("#id"+this.id).val());
    });
    
    //Assign a foreign key to modal window
    $('#formmodal').on('shown.bs.modal', function () {
        $("input[name='fkCcid']").val($("#courseid").val());
        $("input[name='fkStaffid']").val($("#staffid").val());
    });
    
    //Get selected assignment id and assign it to confirm form hidden id
    $("a[title='delete']").click(function(){
        $("input[name='itemid']").val(this.id);
    });
     
    
    
});
</script>
<div class="col col-md-10">
    <h3>Assessment settings</h3>
    <hr>
    <div class="row">
    <div class="col col-md-8">
        <h4><strong>Course :</strong> <?php echo $module->getFkModuleid()->getModuleName(); ?> (<?php echo $module->getFkPeriodid()->getTitle(); ?>) - <?php echo $module->getFkGroupid()->getGroupCode(); ?></h4>

    </div>

    <div class="col col-md-4 text-right">
        <a class="btn btn-primary" href="<?php echo $this->url("examination",array("action"=>"importassessments","id"=>$module->getPkCcid())); ?>">Import settings & marks</a>
        <a class="btn btn-primary" data-toggle="modal" data-target="#formmodal">Create Assessment</a>
    </div>     
    </div>
    <hr>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Assessment Title</th>
                <th>Category</th>
                <th>Weighting(%)</th>
                <th>Date created</th>
                <th>Status</th>
                <th width="160">Controls</th>
            </tr>
        </thead>
        <tbody>
        <?php
        
        foreach($assessments as $assessment){
            if($assessment->getFkAtid()->getSystemGenerated() != 1){
            $createddate = date_format($assessment->getCreatedon(), 'd M Y');
                    
        ?>
        <tr>
            <td><?php echo $assessment->getAssessmentTitle(); ?></td>
            <td><?php echo $assessment->getFkAtid()->getTypeName(); ?></td>
            <td><?php echo $assessment->getWeighting(); ?></td>
            <td><?php echo $createddate; ?></td>
            <td>Status</td>
            <td>
                <a  href="<?php echo $this->url("examination",array("action"=>"grades","id"=>$assessment->getPkAiid())); ?>" class="btn btn-sm btn-info ">Grades</a>
                
                <a title="delete"  data-toggle="modal" data-target="#confirmmodal" id="<?php echo $assessment->getPkAiid(); ?>" class="btn btn-sm btn-info ">Delete</a>
            </td>
        </tr>
        <?php
                    }
        }
        ?>
        </tbody>
    </table>
    <div class="col ">
        <input id="staffid" value="<?php echo $staff->getPkStaffid(); ?>" type="hidden" />
        <input id="courseid" value="<?php echo $module->getPkCcid(); ?>" type="hidden" />
    <form class="form-inline" role="form">
        
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a>
        <a class="btn btn-warning" href="<?php echo $this->url("examination",array("action"=>"exammanagement")); ?>"><i class="glyphicon glyphicon-backward"></i> Return </a>
    </form>    
    </div>

</div>