<div class="row">
        <div class="col col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> - questions</h3>
            <div class="panel-body">
                <a href="<?php echo $this->url("examination",array("action"=>"amgmt")); ?>" class="btn btn-sm btn-warning "><i class="glyphicon glyphicon-arrow-left"></i> Return </a>   
            <hr>
            
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Class</th>
        <th>Module</th>
        <th width="100">Questions</th>
       
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $count = 1;
      foreach($items as $item){
          //$inhand = $total[$module->getFkClassmoduleid()->getPkClassmoduleid()] - $signedoff[$module->getFkClassmoduleid()->getPkClassmoduleid()];
          
      ?>

      <tr>
          <td><?php echo $count; ?></td>
          <td><?php echo $item->getFkAiid()->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
          <td><?php echo sprintf("%s - %s (%s)",$item->getFkAiid()->getAssessmentTitle(),$item->getFkAiid()->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$item->getFkAiid()->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
          <td class="text-right"><?php //echo $item['qnum']; ?></td>
          <td>
              <a href="<?php echo $this->url("examination",array("action"=>"eqm","id"=>$item->getFkAiid()->getPkAiid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-list"></i></a>
             
          </td>
      </tr>
      
      <?php
      $count++;
      }
      
      ?>
    </tbody>
</table>
           
            </div>
                </div>
        </div>
</div>