<div class="row">

        <div class="col col-md-12 ">
            <div class="panel panel-default">
                <h3 class="page-header">Question - Compile marks<?php //echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> </h3>
            <div class="panel-body">
                <a href="<?php echo $this->url("examination",array("action"=>"asq","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-warning "><i class="glyphicon glyphicon-arrow-left"></i> Return </a> <br>
            <hr>
            <form method="POST" action="" name="frmcompute">
                <blockquote class="panel-primary"><?php echo sprintf("%s (%s) - %s",$item->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$item->getFkClassmoduleid()->getFkModuleid()->getModuleCode(),$item->getAssessmentTitle()); ?><div class="pull-right"><input type="submit" name="save" value="Save compiled marks" class="btn btn-sm btn-primary"></div></blockquote>
                <div ng-slimscroll horizontal-scroll="true">            
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
        <th colspan="3"></th>
         <?php
        foreach($papers as $paper=>$q){
        ?>
        <th colspan="<?php echo count($papers[$paper])+1; ?>" class="info text-center"><?php echo $paper; ?></th>
        <?php
            }
        ?>
        
        <th  class="info text-center">Total</th>
        <th  class="info text-center">Average</th>
      </tr>
      <tr>
        <th width="2"></th>
        <th >Registration</th>
        <th nowrap>Student name</th>
        
        <?php
        $questioncount = 1;
        $totalmarkoutof = 0;
        
        
        //foreach($questions as $question){
        foreach ($papers as $paper=>$qheaders){
            $papercount = 1;
            $totalperpaper  = 0;
            //$totalperpaper  += $totalmarkoutof;
            foreach ($qheaders as $question){
                if($papercount < count($papers[$paper])){
        ?>
                <th width="1%" class="text-center"><?php echo $question->getQuestionNumber(); ?><BR>(<?php echo $question->getMarkOutOf(); ?>)</th>
        <?php
                    $totalperpaper += $question->getMarkOutOf();
                }elseif($papercount == count($papers[$paper])){
                    $totalperpaper += $question->getMarkOutOf();
                ?>
                <th width="1%" class="text-center"><?php echo $question->getQuestionNumber(); ?><BR>(<?php echo $question->getMarkOutOf(); ?>)</th>
                <th width="1%" class="text-center"><h4><?php echo $totalperpaper; ?></h4></th>
        <?php
                }
               $papercount++; 
            }
            $totalmarkoutof += $totalperpaper;
        }
        ?>
        <th width="1%" class="text-center"><h4><?php echo $totalmarkoutof; ?></h4></th>
        <th width="7%" class="text-center"><h4>100</h4></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $count = 1;
      foreach($students as $student){
         
      ?>

      <tr>
        <td><?php echo $count; ?></td>
        <td><?php echo $student["REGNUMBER"]; ?></td>
        <td><?php echo sprintf("%s %s",$student["SURNAME"],$student["FIRSTNAME"]); ?></td>

        
        <?php
        $totalMark = 0;
        foreach ($papers as $paper=>$qmarks){
            $studentpapercount = 1;
            $totalpapermark    = 0;
            foreach($qmarks as $qmark){
                if($studentpapercount < count($papers[$paper])){
        ?>
                <td align="center"><?php echo $marks[$student["STUDENTCLASSID"]][$qmark->getPkQid()]; ?></td>
        <?php
                    $totalpapermark += $marks[$student["STUDENTCLASSID"]][$qmark->getPkQid()];
                }else{
                    $totalpapermark += $marks[$student["STUDENTCLASSID"]][$qmark->getPkQid()];
        ?>
                <td align="center"><?php echo $marks[$student["STUDENTCLASSID"]][$qmark->getPkQid()]; ?></td>
                <td align="center" style="background-color: white"><h4><?php echo $totalpapermark; ?></h4></td>
        <?php
                }
                $studentpapercount++;
            }
            $totalMark += $totalpapermark; 
         }
        ?>
        <td align="right" ><h4><?php echo $totalMark; ?></h4></td>
        <td align="right" ><input class="form-control" type="text" readonly="" name="studentmark[<?php echo $student["STUDENTCLASSID"]; ?>]" value="<?php echo round(($totalMark/$totalmarkoutof)*100); ?>" /></td>
      </tr>
      
      <?php
      $count++;
     }
      
      ?>
    </tbody>
</table>
                </div>         
        <div class="pull-right"><input type="submit" name="save" value="Save" class="btn btn-sm btn-primary"></div>   
            </form>
            </div>
                </div>
        </div>
</div>
        