<div class="row">
<div class="col col-md-2">
    &nbsp;
    </div>
    <form method="POST">
        <div class="col col-md-8">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s (%s)",$item->getAssessmentTitle(),$item->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?> - confirm import</h3>
            <div class="panel-body">
                <div class="alert alert-info">
                    <ul>
                        <li>The following marks will be captured in the system. Click <strong>Save</strong> button to complete to upload or <strong>Discard</strong> to cancel upload.</li>
                        <li>All entries with errors will not be uploaded until the errors are corrected.</li>
                    </ul>    
                </div>
                &nbsp;<button type="submit" name="btnupload" value="1"  class="btn btn-sm btn-success"><i class="glyphicon glyphicon-save"></i> Save </button>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"im","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-remove"></i> Discard </a>
            <hr>
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Student number</th>
        <th width="100">Mark</th>
        <th width="120">Status</th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($list as $student){
      ?>
      <tr>
          <td><?php echo $student['STUDENTNUMBER']; ?></td>
         
        <td align="right"><?php echo $student['MARK']; ?></td>
        <td><?php echo implode("<li>",$student['ERRORS']); ?></td>
      </tr>
     
      <?php
      }
      
      ?>
    </tbody>
</table>
       <hr>
       <button type="submit" name="btnupload" value="1"  class="btn btn-sm btn-success"><i class="glyphicon glyphicon-save"></i> Save </button>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"importmarks","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-remove"></i> Discard </a>
            </div>
                </div>
        </div>
    </form>
</div>
        