<div class="row">
        <div class="col col-md-12 ">
            <div class="panel panel-default">
            <h3 class="page-header">Examination management</h3>
            <div class="panel-body">
            
            <hr>
            
            <div class="row">
                <div class="col-md-3">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Examination results publishing</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/ok.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                                Manage examination results publishing
                                <p></p>
                                <a href="<?php echo $this->url("administration",array("action"=>"users")); ?>" class="btn btn-sm btn-info">Manage</a>
                                
                            </div>
                        </div>    
                    </div>
                    
                </div>
                <div class="col-md-3">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Examination numbers</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/number.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                                Generate student examination numbers
                                <p></p>
                                <a href="<?php echo $this->url("administration",array("action"=>"users")); ?>" class="btn btn-sm btn-info">Manage</a>
                                
                            </div>
                        </div>    
                    </div>
                    
                </div>
                <div class="col-md-3">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Examination period setup</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/calendar.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                                Set period for managing examination
                                <p></p>
                                <a href="<?php echo $this->url("administration",array("action"=>"users")); ?>" class="btn btn-sm btn-info">Setup</a>
                                
                            </div>
                        </div>    
                    </div>
                    
                </div>
                <div class="col-md-3">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Grade flow</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/check.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                               Setup module flow of grades in the system.
                                <p></p>
                                <a href="<?php echo $this->url("examination",array("action"=>"gf")); ?>" class="btn btn-sm btn-info">Setup</a>
                                
                            </div>
                        </div> 
                    </div>
                </div>
               
            </div>

            </div>
                </div>
        </div>
    </div>