<div class="col col-md-10">
    <h3>Capture Grades</h3>
    <hr>
    <div class="row">
    <div class="col col-md-8">
        <h4><strong><?php echo $assessment->getAssessmentTitle(); ?> :</strong> <?php echo $assessment->getFkCcid()->getFkModuleid()->getModuleName(); ?> (<?php echo $assessment->getFkCcid()->getFkPeriodid()->getTitle(); ?>)</h4>

    </div>
<div class="col col-md-4 text-right">
    
    
    <a class="btn btn-warning" href="<?php echo $this->url("examination",array("action"=>"capturegrades","id"=>$assessment->getFkCcid()->getPkCcid())); ?>"><i class="glyphicon glyphicon-backward"></i> Assessments</a></div>
    </div>     

    <hr>
    <?php
    $frmgrades->setAttributes(array('autocomplete'=>'off','id'=>'frmapplication'))->prepare();;
    echo $this->form()->openTag($frmgrades); 
    ?>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Registration #</th>
                <th>Last name</th>
                <th>First name</th>
                <th width="60">Gender</th>
                <th width="80">Grade</th>
            </tr>
        </thead>
        <tbody>
        <input name="fkStaffid" type="hidden" value="<?php echo $assessment->getFkStaffid()->getPkStaffid(); ?>" />
        <input name="fkAiid" type="hidden" value="<?php echo $assessment->getPkAiid(); ?>" />
        <?php

        foreach($frmgrades->get('mark')->getIterator() as $key=>$markfield){
            $studentid = $students[$key]['CLASS']->getFkStudentid()->getPkStudentid();
            $mark      = (!empty($marks[$studentid]['mark']))?$marks[$studentid]['mark']:'';
            $id        = (!empty($marks[$studentid]['id']))?$marks[$studentid]['id']:'';
        ?>
        <tr>
            <td><?php echo $students[$key]['PROGRAM']->getRegistrationNumber(); ?></td>
            <td><input name="student[<?php echo $key; ?>]" type="hidden" value="<?php echo $studentid; ?>" />
                <input name="pkSmid[<?php echo $key; ?>]" type="hidden" value="<?php echo $id; ?>" />
                <?php echo $students[$key]['CLASS']->getFkStudentid()->getFkUserid()->getSurname(); ?></td>
            <td><?php echo $students[$key]['CLASS']->getFkStudentid()->getFkUserid()->getFirstname(); ?></td>
            <td><?php echo $students[$key]['CLASS']->getFkStudentid()->getFkUserid()->getGender(); ?></td>
            <td>
            <?php  echo $this->formElement($markfield->get('mark')->setValue($mark)); ?>
            </td>
        </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
    <div class="col " class="form-inline">
        <button name="btnSave" value="1" id="btnSave" class="btn btn-success"><span class="glyphicon glyphicon-floppy-save " aria-hidden="true"></span>&nbsp;Save grades</button>
        
        <a class="btn btn-warning" href="<?php echo $this->url("examination",array("action"=>"capturegrades","id"=>$assessment->getFkCcid()->getPkCcid())); ?>">Cancel</a>    
    </div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>