<div class="row">
<div class="col col-md-2">
    &nbsp;
    </div>
        <div class="col col-md-8">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s (%s)",$item->getAssessmentTitle(),$item->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?> - import marks</h3>
            <div class="panel-body">
                
                &nbsp;<a href="<?php echo $this->url("examination",array("action"=>"cam","id"=>$item->getPkAiid())); ?>" class="btn btn-sm btn-warning pull-left"><i class="glyphicon glyphicon-backward"></i> Return </a>
            <hr>
            <div class="alert alert-info">
                <ul>
                    <li>Put list of students with their respective marks in a spreadsheet in this format <a href="#">Click here</a></li>
                    <li>Save the spreadsheet fie using Comma Delimited format (CSV). * Note: headers should be included when uploading the file. </li>
                    <li>Use <strong>Choose file</strong> button below to locate the CSV file </li>
                    <li>Click <strong>Upload</strong> button to upload the list  </li>
                </ul>
            </div>
            <div class="row">
                <?php
                $uploadform->setAttributes(array('id'=>'formupload'))->prepare();
                echo $this->form()->openTag($uploadform);
                ?>
                <div class="col col-md-4">
                    <?php echo $this->formElement($uploadform->get('File')->get('filename')); ?>
                </div>
                <div class="col col-md-4">
                    <input type="hidden" value="<?php echo $item->getPkAiid(); ?>" name="item" />
                    <button name="btnupload" class="btn btn-sm btn-primary" value="1"><i class="glyphicon glyphicon-upload"></i> Upload</button>
                </div>
                <?php
                echo $this->form()->closeTag();
                ?>
            </div>
       <hr>
      
            </div>
                </div>
        </div>
</div>
        