<div class="col col-md-10">
    <h3>Assessments import</h3>
    <hr>
    <div class="col col-md-8 text-left">
        <h4><strong>Course :</strong> <?php echo $module->getFkModuleid()->getModuleName()."({$module->getFkPeriodid()->getTitle()}) - {$module->getFkGroupid()->getGroupCode()}"; ?></h4>   
    </div>
    <div class="col  text-right">
        <a href="<?php echo $this->url("examination",array("action"=>"capturegrades","id"=>$module->getPkCcid())); ?>" class="btn btn-warning"><i class="glyphicon glyphicon-backward"></i> Assessments</a>  
    </div>
    <hr>
    <p class="text-primary">Note: Table below is the format of an upload file. Use the upload file key below to populate some of the upload file fields. </p>    
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Type</th>
                <th>Short title</th>
                <th>Weighting</th>
               
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>Assignment 1</td>
            <td>ASS</td>
            <td>Assign</td>
            <td>80</td>          
        </tr>
         <tr>
            <td>KA1136</td>
            <td>78</td>
            <td></td>
            <td></td>          
        </tr>
        
        </tbody>
    </table>

    <div class="col col-md-7">
        <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Upload file key</strong></div>
            <div class="panel-body">
               
                <div class="col-sm-3  text-right">
                    <strong>Type :</strong>
                </div>
                <div class="col-sm-9">
                    <?php
                    foreach($assessmenttypes as $assessmenttype){
                     echo $assessmenttype->getTypeCode(); 
                    ?>
                    <br>
                    <?php
                    }
                    ?>
                </div> 
                <hr>
            </div>
        </div>        
    </div> 
    </div>
    
    <div class="col col-md-5">
        <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Assignment upload</strong></div>
            <div class="panel-body">
                <?php
                $uploadform->setAttributes(array('id'=>'formupload'))->prepare();
                echo $this->form()->openTag($uploadform);
                ?>
                
                    
                    <div class="alert alert-info">   
                        Click the 'Upload file' button to start the uploading process.
                    </div>
                    
                    <div class="form-group">   
                        <div class="col-sm-4"><strong><?php echo $this->formLabel($uploadform->get('File')->get('filename')); ?></strong></div>
                       <div class="col-sm-6">
                           <strong><?php echo $this->formElement($uploadform->get('File')->get('filename')); ?>
                       </div>
                       <div class="col-sm-2"></div>
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-4"></div>
                       <div class="col-sm-3" >
                           <input type="hidden" name="fkCcid" value="<?php echo $module->getPkCcid(); ?>" />
                           <br />
                           <input type="submit" name="btnupload" class="btn btn-success" value="Upload File" />
                           
                       </div>
                       <div class="col-sm-2"><br /><a class="btn btn-warning" href="<?php echo $this->url("examination",array("action"=>"capturegrades","id"=>$module->getPkCcid())); ?>">Cancel</a> </div>
                    </div>                            
                <?php
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>        
    </div>        
       
    </div> 
</div>