<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Examination reports</h3>
            <div class="panel-body">
            
            <div class="row">
                
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading">List of available reports</div>
                        <div class="list-group">
                              <!-- START list group item-->
                              <a  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                              <h4>Grade book</h4>
                                              Generate grade book for an academic period.
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                              <a  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Student result notifications</h4>
                                              Generate result notification for students
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                              <a  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Academic transcripts</h4>
                                              Produce student academic transcript
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                               <a  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Annual performance rate</h4>
                                              Produce student academic transcript
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              <a  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Dean's list</h4>
                                              Generate dean's list
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                               
                        </div>
                        
                    </div>
                </div>
               
            </div>

            </div>
                </div>
        </div>
    </div>