
<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <h4 class="page-header">Lecturer module allocation</h4>
                    <div class="panel-body">
                        <div class="alert alert-info"><strong><?php echo sprintf("%s - %s (%s)",$module->getFkClassid()->getClassCode(),  strtoupper($module->getFkModuleid()->getModuleName()),$module->getFkModuleid()->getModuleCode()); ?></strong></div>
<?php
    
    if(!empty($details)){
        $staffid = !empty($details->getFklmid())?$details->getFklmid()->getFkStaffid()->getPkStaffid():$details->getFlag();
    }else{
        $staffid = $form->get('Servicedmodule')->get('fkStaffid')->getValue();
    }
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    
 ?>
     <div class="row form-group" >   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Servicedmodule')->get('fkStaffid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Servicedmodule')->get('fkStaffid')->setValue($staffid));
                 echo $this->formElement($form->get('Servicedmodule')->get('pkLmid'));
           ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Servicedmodule')->get('fkStaffid')); ?></div>
    </div>
    
    <div class="form-group" >   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("examination",array("action"=>"lecturermodule")); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>