<div class="col col-md-10">
    <h3>Page Title</h3>
    <hr>
    <div class="col text-right"><a href="<?php echo $this->url("finance",array("action"=>"add")); ?>" class="btn btn-primary">Add New Item</a>  </div>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>John</td>
            <td>Doe</td>
            <td>john@example.com</td>
        </tr>
        <tr>
            <td>Mary</td>
            <td>Moe</td>
            <td>mary@example.com</td>
        </tr>
        <tr>
            <td>July</td>
            <td>Dooley</td>
            <td>july@example.com</td>
        </tr>
        </tbody>
    </table>
    <div class="col ">
    <form class="form-inline" role="form">
        <div class="form-group">
            <label for="email">Show:</label>
            <select class="form-control">
            <option>10</option>
            <option>20</option>
            <option>30</option>
            <option>50</option>
            <option>100</option>
            </select> 
        </div>
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
    </form>    
    </div>
</div>
        