<script type="text/javascript">
    $(document).ready(function(){
        $('#studentlist').slimscroll({
            height: '300px',
            width: 'auto'
          });
    });
</script>
<div class="col col-md-10">
    <h3>Class attendance</h3>
    <hr>
    <div class="col col-md-11">
        <div class="alert alert-info"><i class="glyphicon glyphicon-info-sign"></i> All fields with * are required</div>
        <div class="panel">
            
            
            <div class="panel-body">
            <?php
        foreach($modules as $module){
        ?>
                <fieldset><legend><blockquote class="panel-warning"><?php echo $module->getFkCcid()->getFkModuleid()->getModuleName(); ?> (<?php echo $module->getFkCcid()->getFkGroupid()->getGroupName(); ?>) <a href="<?php echo $this->url("admission",array("action"=>"classregister","id"=>$module->getPkLmid()));?>" class="btn btn-sm btn-success pull-right"><i class="glyphicon glyphicon-user"></i> Set attendance</a></blockquote></legend>
                    <?php //echo $this->formHidden($frmregister->get('Student')->get('pkStudentid')); ?>
                    <div class="form-group">   
                       <div class="col-sm-2">
                           <?php //echo $this->formLabel($frmregister->get('Student')->get('biodata')->get('surname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php //echo $this->formElement($frmregister->get('Student')->get('biodata')->get('surname')); ?>
                       </div>
                       <div class="col-sm-4"><?php //echo $this->formElementErrors($frmregister->get('Student')->get('biodata')->get('surname')); ?></div>
                    </div>
                </fieldset>
                
                <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>


<div id="formattendance" class="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
  <?php
//  $form->setAttributes(array('id'=>'formsubmit'));
//  echo $this->form()->openTag($form);
 
  ?>
    <div class="modal-dialog modal-body">
        
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="formtitle">Class attendance<span id="user"></span></h4>
        </div>
        <div class="modal-body">
            <div class="alert alert-info" role="alert">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                
                All fields are required
              </div>
             
            <div class="alert alert-success" id="success" role="alert"></div>
            <div class="alert alert-danger" id="warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
            </div>
            
            <div> 
                <input type="text" class="form-control" name="classdate" placeholder="Lesson date" />
            </div>
            <p>&nbsp;</p>
            <div id="studentlist">
                
                <table width="100%" class="table table-bordered table-striped">
                    <thead>
                    <tr><th>&nbsp;</th><th>Reg #</th><th>Surname</th><th>Firstname</th><th>Gender</th>
                    </tr>
                    </thead>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" /></td><td>BME233</td><td>Kumwembe</td><td>Humphrey</td><td>Male</td>
                    </tr>
                </table>
                
            </div>
            
            
        </div>
       <div class="modal-footer">
           <button name="btnSave" value="1" id="btnSave" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-floppy-save " aria-hidden="true"></span>&nbsp;Save</button>
      </div>
    </div>
  </div>
 <?php
 echo $this->form()->closeTag();
 ?>
    
</div>

        