<div class="col col-md-10">
    <h3>Enrollment confirmation</h3>

    <hr>
    
    <table class="table table-bordered table-hover" id="tblData">
        <thead>
            <tr>
                <th>Serial</th>
                <th>Student #</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Initial</th>
                <th>Gender</th>
                <th>Email address</th>
                <th>Class/Group</th>
                <th>Year joined</th>
                <th>Entry manner</th>
                <th>Study mode</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $counter = 1;
        foreach($list as $student){
            
        ?>
        <tr>
            <td><?php echo $counter; ?></td>
            <td><?php echo !empty($student['studentdata']['studentno'])?$student['studentdata']['studentno']:"<span class='text-danger'><i>".$student['error']['studentno']."</i></span>"; ?></td>
            <td><?php echo !empty($student['studentdata']['firstname'])?$student['studentdata']['firstname']:"<span class='text-danger'><i>".$student['error']['firstname']."</i></span>"; ?></td>
            <td><?php echo !empty($student['studentdata']['surname'])?$student['studentdata']['surname']:"<span class='text-danger'><i>".$student['error']['surname']."</i></span>"; ?></td>
            <td><?php echo $student['studentdata']['initial']; ?></td>
            <td><?php echo !empty($student['studentdata']['gender'])?$student['studentdata']['gender']:"<span class='text-danger'><i>".$student['error']['gender']."</i></span>"; ?></td>
            <td><?php echo $student['studentdata']['emailaddress']; ?></td>
            <td><?php echo !empty($student['studentdata']['groupname'])?$student['studentdata']['groupname']:"<span class='text-danger'><i>".$student['error']['class']."</i></span>"; ?></td>
            <td><?php //echo $student->getYearjoined(); ?></td>
            <td><?php echo !empty($student['studentdata']['entrymanner'])?$student['studentdata']['entrymanner']:"<span class='text-danger'><i>".$student['error']['entrymanner']."</i></span>"; ?></td>
            <td><?php echo !empty($student['studentdata']['studymodetitle'])?$student['studentdata']['studymodetitle']:"<span class='text-danger'><i>".$student['error']['studymode']."</i></span>"; ?></td>
            <td><?php echo !empty($student['error']['emailaddress'])?"<span class='text-danger'><i>".$student['error']['emailaddress']."</i></span>":""; ?></td>
        </tr>
       <?php
        $counter++;
        }
       ?>
        </tbody>
    </table>
    <div class="col ">
        <form class="form-inline" role="form" method="POST">
            <a class="btn btn-success" href="<?php echo $this->url("admission",array("action"=>"saveenrolledlist")); ?>">Continue <i class="glyphicon glyphicon-disk"></i></a> 
    </form>    
    </div>
</div>
        