<div class="col col-md-10">
    <h3>Enrollment</h3>
    <hr>
    <div class="row">
    <div class="col col-md-8">
        
        <form name="frmsearch" class="form-inline  text-left" role="form" method="POST">
        <div class="form-group">
            <input name="itemcount" type="hidden" />
            <label for="email">Filter search:</label>
            <select class="form-control" name="class">
                <option value="">--Class--</option>
            <?php
            foreach ($classes as $class){
            ?>
            <option value="<?php echo $class->getPkGroupid(); ?>"><?php echo $class->getGroupName(); ?></option>
            <?php
            }
            ?>
            </select> 
        </div>
        <div class="form-group">
            <select class="form-control" name="period">
                <option value="">--Period--</option>
            <?php
            foreach ($academicperiod as $period){
            ?>
            <option value="<?php echo $period->getPkPeriodid(); ?>"><?php echo $period->getTitle(); ?></option>
            <?php
            }
            ?>
            
            </select> 
        </div> 
         
         <input type="submit" name="search" value="Show Data" class="btn btn-primary">
    </form>        

    </div>

    <div class="col col-md-4 text-right">
        <a class="btn btn-primary" href="<?php echo $this->url("admission",array("action"=>"groupenrollment")); ?>">Group</a>
        <a class="btn btn-primary" href="<?php echo $this->url("admission",array("action"=>"individualenrollment")); ?>">Individual</a>
    </div>
</div>
    <hr>
    <div class="msgcontainer alert alert-warning">
        Test
    </div>
    <form id="frmauto-register" method="POST" action="<?php echo $this->url("admission",array("action"=>"autoregister")); ?>">
    <table class="table table-bordered table-hover" id="searchable">
        <thead>
            <tr>
                <th><input type="checkbox" class="checkbox" name="selecttall" /></th>
                <th>Student #</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Initial</th>
                <th>Gender</th>
                <th>Email address</th>
                <th>Class/Group</th>
                <th>Year joined</th>
                <th>Entry manner</th>
                <th>Study mode</th>
            </tr>
        </thead>
        <tbody>
        
        <?php
        foreach($enrolledlist as $student){
        ?>
        <tr>
            <td><input class="checkbox" type="checkbox" name="chkStudentid[]" value="<?php echo $student->getPkEnrollmentid(); ?>" /></td>
            <td><?php echo $student->getTempstudentno(); ?></td>
            <td><?php echo $student->getFirstname(); ?></td>
            <td><?php echo $student->getSurname(); ?></td>
            <td><?php echo $student->getInitial(); ?></td>
            <td><?php echo $student->getGender(); ?></td>
            <td><?php echo $student->getEmailaddress(); ?></td>
            <td><?php echo $student->getFkGroupid()->getGroupCode(); ?></td>
            <td><?php echo date_format($student->getYearjoined(), "Y"); ?></td>
            <td><?php echo $student->getFkEntrymannerid()->getEntryName(); ?></td>
            <td><?php echo $student->getFkStudymode()->getTitle(); ?></td>
        </tr>
       <?php
        }
       ?>
        
        </tbody>
    </table>
    </form>
    <div class="col ">
        <form class="form-inline" role="form" method="POST">
        <div class="form-group">
            <label for="email">Show:</label>
            <select class="form-control" name="pageitems">
            <option>10</option>
            <option>20</option>
            <option>30</option>
            <option>50</option>
            <option>100</option>
            </select> 
        </div>
            <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> <button id="auto-register" name="auto-register" class="btn btn-info">Auto register <i class="glyphicon glyphicon-check"></i></button> 
    </form>    
    </div>
</div>
        