<div class="col col-md-10">
    <h3>Generate Registration Numbers</h3>
    <hr>
    <div class="col col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Select Group</strong></div>
            <div class="panel-body">
                <form action="" class="form-inline" role="form" > 
                    <div class="form-group">   
                       Display group *
                       
                           <select  class="form-control">
                               <option>--Select group--</option>
                               <option>IMIS 1</option>
                               <option>ACCA 1</option>
                           </select>
                       
                       
                           <input type="submit" class="btn btn-success" value="Select Data" />
                       
                       <div class="col-sm-4"></div>
                    </div>
                           
                </form>
            </div>
        </div>
    </div>
    
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th width="20px">Select</th>
                <th>Firstname</th>
                <th>Lastname</th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td><input type="checkbox"></td>
            <td>John</td>
            <td>Doe</td>
        </tr>
        </tbody>
    </table>    
    <div class="col ">
    <form class="form-inline" role="form">
        <input type="button" class="btn btn-primary" value="Generate">
    </form>    
    </div>    
</div>
        