<script>
/* Script written by Adam Khoury @ DevelopPHP.com */
/* Video Tutorial: http://www.youtube.com/watch?v=EraNFJiY0Eg */
function _(el){
	return document.getElementById(el);
}
function uploadFile(){
	//var file = _("file1").files[0];
	// alert(file.name+" | "+file.size+" | "+file.type);
	var formdata = new FormData();
	//formdata.append("file1", file);
	var ajax = new XMLHttpRequest();
	ajax.upload.addEventListener("progress", progressHandler, false);
	ajax.addEventListener("load", completeHandler, false);
	ajax.addEventListener("error", errorHandler, false);
	ajax.addEventListener("abort", abortHandler, false);
	ajax.open("POST", "/smis/public/admission/testing");
	ajax.send(formdata);
        return false;
}
function progressHandler(event){
	_("loaded_n_total").innerHTML = "Uploaded "+event.loaded+" bytes of "+event.total;
	var percent = (event.loaded / event.total) * 100;
	_("progressBar").value = Math.round(percent);
	_("status").innerHTML = Math.round(percent)+"% uploaded... please wait";
}
function completeHandler(event){
	_("status").innerHTML = event.target.responseText;
	_("progressBar").value = 0;
}
function errorHandler(event){
	_("status").innerHTML = "Upload Failed";
}
function abortHandler(event){
	_("status").innerHTML = "Upload Aborted";
}
</script>
<div class="row">
        <div class="col col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            <h3 class="page-header">Auto generate registration numbers</h3>
            <div class="panel-body">
            
            <hr>
            <h4>Parameters:</h4>
            
            <div class="row">
                <progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
                <h3 id="status"></h3>
                <p id="loaded_n_total"></p>
                <?php
                $form->setAttributes(array('id'=>'formsubmit'))->prepare();
                echo $this->form()->openTag($form);
                ?>
                
                   
                <hr>
                    <?php
                    foreach($form->get('Registration')->get('process_steps')->getValueOptions() as $value=>$label){
                    ?>
                    <div class="row">   
                       <div class="col col-md-8 col-md-offset-2">
                           <input <?php if($value != 4){?> checked <?php } ?> type="checkbox" name="<?php echo $form->get('Registration')->get('process_steps')->getName(); ?>[]" value="<?php echo $value; ?>">
                                   <?php echo $label; ?>
                       </div>
                    </div> 
                   <?php
                   }
                   ?>
                    <hr>
                    <div class="row">   
                       <div class="col col-md-6">
                           &nbsp;
                           <input type="submit" name="btngenerate" class="btn btn-sm btn-info" value="Start process" />
                           <a href="<?php echo $this->url("admission",array("action"=>"selectionlist")); ?>" class="btn btn-sm btn-warning">Cancel</a>
                       </div>
                    </div>                            
                <?php
                echo $this->form()->closeTag();
                ?>
                
            </div>

            </div>
                </div>
        </div>
    </div>