<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Admission dashboard</h3>
            <div class="panel-body">
            
            <hr>
            
            <div class="row">
                <div class="col-md-5">
                    
                    <div class="panel panel-primary">
                        
                        <div class="panel-body">
                            <?php $pie->printScripts(); ?>
                            <div id="container"></div>
                            <script type="text/javascript"><?php echo $pie->render("chart1"); ?></script>
                        </div>    
                    </div>
                    
                </div>
                <div class="col-md-7">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <?php $bar->printScripts(); ?>
                            <div id="barcontainer"></div>
                            <script type="text/javascript"><?php echo $bar->render("chart2"); ?></script>
                        </div> 
                    </div>
                </div>
            </div>

            </div>
                </div>
        </div>
    </div>