<div class="col col-md-10">
    <h3>Individual Student Enrollment</h3>
    <hr>
    <div class="col col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Enrollment Details</strong></div>
            
            <div class="panel-body">
            <?php
            $formenrollment->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmlogin'))->prepare();;
            echo $this->form()->openTag($formenrollment);
            ?>
                <fieldset><legend>Personal information</legend>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($formenrollment->get('Enrollment')->get('basicdetails')->get('surname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($formenrollment->get('Enrollment')->get('basicdetails')->get('surname')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($formenrollment->get('Enrollment')->get('basicdetails')->get('surname')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($formenrollment->get('Enrollment')->get('basicdetails')->get('firstname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($formenrollment->get('Enrollment')->get('basicdetails')->get('firstname')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($formenrollment->get('Enrollment')->get('basicdetails')->get('firstname')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($formenrollment->get('Enrollment')->get('basicdetails')->get('initial')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($formenrollment->get('Enrollment')->get('basicdetails')->get('initial')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php //echo $this->formElement($formenrollment->get('Enrollment')->get('initial')); ?>
                       </div>
                      
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('basicdetails')->get('gender')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('basicdetails')->get('gender')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('dob')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('dob')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('basicdetails')->get('emailaddress')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('basicdetails')->get('emailaddress')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($formenrollment->get('Enrollment')->get('basicdetails')->get('emailaddress')); ?></div>
                    </div>
                </fieldset>
                
                <fieldset><legend>Program of study information</legend>
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('fkGroupid')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('fkGroupid')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('fkPeriodid')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('fkPeriodid')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    
                   <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('fkEntrymannerid')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('fkEntrymannerid')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($formenrollment->get('Enrollment')->get('fkStudymodeid')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($formenrollment->get('Enrollment')->get('fkStudymodeid')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    </fieldset>
                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Save Data" />
                           <input name="cancel" type="submit" class="btn btn-warning" value="Cancel" />
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
        