<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Admission reports</h3>
            <div class="panel-body">
            
            <div class="row">
                
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading">List of available reports</div>
                        <div class="list-group">
                              <!-- START list group item-->
                              <a href="<?php echo $this->url("admission",array("action"=>"es")); ?>" class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                              <h4>Enrollment statistics</h4>
                                              Generate student enrollment statistics
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                              <a href="<?php echo $this->url("admission",array("action"=>"ad")); ?>"  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Age distribution</h4>
                                              Generate students age distribution
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                              <a href="<?php echo $this->url("admission",array("action"=>"ed")); ?>"  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Early Dropout</h4>
                                              Generate report on deceased, suspended, dropout students
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              
                               <a href="<?php echo $this->url("admission",array("action"=>"gd")); ?>"  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Graduands</h4>
                                              Graduands report
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              <a href="<?php echo $this->url("admission",array("action"=>"na")); ?>"  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Nationality/district/region</h4>
                                              Nationality report
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a>
                              <a href="<?php echo $this->url("admission",array("action"=>"scp")); ?>"  class="list-group-item">
                                 <div class="media">
                                    
                                    <div class="media-body clearfix">
                                       
                                      <div class="alert alert-primary">
                                          <div class="col col-md-2"><img src="<?php echo $this->basePath(); ?>/img/report-icon.png" width="60" alt="" class="img-thumbnail" /></div>
                                          
                                          <div class="col col-md-10">
                                             <h4>Scholarships</h4>
                                              Scholarship reports
                                         </div>
                                          
                                      </div>
                                       <div ></div>
                                    </div>
                                 </div>
                              </a> 
                        </div>
                        
                    </div>
                </div>
               
            </div>

            </div>
                </div>
        </div>
    </div>