
<div class="row">
        <div class="col col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            <h3 class="page-header">Admission reports: Scholarships</h3>
            <div class="panel-body">
            <h4 class="text-danger text-uppercase"><?php //echo $title; ?></h4>
            
            <table class="table table-bordered table-striped table-hover">
    <thead>
     
      <tr>
        <th class="text-center"></th>
        <th class="text-center">Status</th>
            <th class="text-center">F</th>
            <th class="text-center">M</th>
            <th class="text-center">T</th>
      </tr>
    </thead>
    <tbody>
      <?php
      //$totals = array();
      foreach($content as $sponsorship){
     ?>
      <tr>
         <th class="text-left"><?php echo $sponsorship['SNAME']; ?></th>
         <th class="text-left" width="30"><?php echo (!$sponsorship['SSTATUS'])?"Retired":"Active"; ?></th>
        <?php
        //foreach($headers as $header){  
        ?>
        <td class="text-center" width="50"><?php echo $sponsorship['F']; ?></td>
        <td class="text-center" width="50"><?php echo $sponsorship['M']; ?></td>
        <td class="text-center" width="70"><strong><?php echo $sponsorship['F']+$sponsorship['M']; ?></strong></td>
        <?php
      //}
      ?>
      </tr>
      <?php
            }
      ?>
    </tbody>
</table>

            </div>
                </div>
        </div>
</div>
        