<div class="col col-md-10">
    <h3>Upload new regulations</h3>
    <hr>
    <div class="col col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Regulations Details</strong></div>
            
            <div class="panel-body">
                <?php
            $formupload->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmlogin'))->prepare();;
            echo $this->form()->openTag($formupload);
            ?>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($formupload->get('Enrollment')->get('surname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($formupload->get('Enrollment')->get('surname')); ?>
                       </div>
                    </div>
                
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($formupload->get('Enrollment')->get('surname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($formupload->get('Enrollment')->get('surname')); ?>
                       </div>
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Save Data" />
                           <input name="cancel" type="submit" class="btn btn-warning" value="Cancel" />
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
        