<div class="row">
            <div class="col col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <h3 class="page-header text-center">Log in to Your Account</h3>
                    
                    <div class="panel-body">
                        <?php
                        if(!empty($errormessage)){
                        ?>
                        <div class="alert alert-danger"><?php echo implode("<li>",$errormessage); ?></div>
                   <?php
                        }
    $frmlogin->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmlogin'))->prepare();;
    echo $this->form()->openTag($frmlogin);
    ?>
                       
    <div class="form-group">   
       <div class="col-sm-12">
           <?php echo $this->formElement($frmlogin->get('Login')->get('username')); ?>
       </div>
    </div>

    <div class="form-group">   
       <div class="col-sm-12">
            <?php echo $this->formElement($frmlogin->get('Login')->get('password')); ?>
       </div>
    </div>

    <div class="form-group">   
       <div class="col-sm-12 text-center">
           <input type="submit" class="btn btn-success " value="Login" />
       </div>
       <div class="col-sm-4"></div>
    </div>                            
                     <?php
    echo $this->form()->closeTag();
    ?>
                        <a href="">Forgot password?</a>
                    
                    </div>
                </div>
            </div>
    </div>