
            <div class="col col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>User Login</h4></div>
                    <div class="panel-body">
                        <form action="" class="form-horizontal" role="form" > 
    <div class="form-group">   
       <div class="col-sm-3">Username *</div>
       <div class="col-sm-5">
           <input class="form-control" />
       </div>
       <div class="col-sm-4"></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3">Password *</div>
       <div class="col-sm-5">
            <input class="form-control" />
       </div>
       <div class="col-sm-4"></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" class="btn btn-success" value="Save Data" />
           <input type="submit" class="btn btn-warning" value="Cancel" />
       </div>
       <div class="col-sm-4"></div>
    </div>                            
                    </form>
                    
                    </div>
                </div>
            </div>