<div class="row">
            <div class="col col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <h3 class="page-header text-center">Renew account password</h3>
                    <div class="panel-body">
                   <?php
    $form->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmlogin'))->prepare();
    echo $this->form()->openTag($form);
    ?>
                       
    <div class="form-group">   
       <div class="col-sm-12">
           <?php echo $this->formElement($form->get('Password')->get('password')); ?>
           <?php echo $this->formHidden($form->get('Password')->get('pkUserid')->setValue($userid)); ?>
       </div>
    </div>

    <div class="form-group">   
       <div class="col-sm-12">
           <?php echo $this->formElement($form->get('Password')->get('cpassword')); ?>
       </div>
    </div>

    <div class="form-group">   
       <div class="col-sm-12 text-center">
           <input type="submit" class="btn btn-success " value="Renew password" />
           <a href="<?php echo $this->url("login",array("action"=>"index")); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
                 <?php
    echo $this->form()->closeTag();
    ?>
                        
                    
                    </div>
                </div>
            </div>
    </div>