<div class="panel">
    <div class="panel-body">
    <h3><?php echo $studentinfo->getFkStudentid()->getFkUserid()->getFirstname()." ".$studentinfo->getFkStudentid()->getFkUserid()->getSurname(); ?>: </h3>
    </div>
    </div>
<div class="col col-md-10">

    <div class="col col-md-11">
        <div class="alert alert-info"><i class="glyphicon glyphicon-info-sign"></i> All fields with * are required</div>
        <div class="panel">
            
            
            <div class="panel-body">
            <?php
            $frmpassword->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmregister'))->prepare();;
            echo $this->form()->openTag($frmpassword);
            ?>
                <fieldset><legend><blockquote class="panel-warning">Set password for account. <span class="text-danger">Your Username/Login ID/Registration number is <?php echo $studentinfo->getRegistrationNumber(); ?></span>  </blockquote></legend>
                    <?php echo $this->formHidden($frmpassword->get('Password')->get('pkUserid')->setValue($studentinfo->getFkStudentid()->getFkUserid()->getPkUserid())); ?>
                   
                    <div class="form-group">   
                       <div class="col-sm-2">
                           <?php echo $this->formLabel($frmpassword->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($frmpassword->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php echo $this->formElementErrors($frmpassword->get('Password')->get('password')); ?>
                       </div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-2">
                           <?php echo $this->formLabel($frmpassword->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($frmpassword->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php echo $this->formElementErrors($frmpassword->get('Password')->get('cpassword')); ?>
                       </div>
                      
                    </div>

                   
                    
                </fieldset>
                
                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Complete registration" />
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
        