<nav class="navbar navbar-submenu">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="#"><a href="<?php echo $this->url("admission",array("action"=>"index")); ?>">Register</a></li>
                    
                    <li><a href="<?php echo $this->url("admission",array("action"=>"sl")); ?>">Student listing</a></li>
                    <li><a href="<?php echo $this->url("admission",array("action"=>"classlist")); ?>">Class list</a></li>
                    <li><a href="#">Cohorts/Short courses</a></li>
                    <li><a href="<?php echo $this->url("admission",array("action"=>"selectionlist")); ?>">Selection list</a></li>
                    <li><a href="#">Request module</a></li>
                    <li><a href="#">Check lists</a></li>
                    <li><a href="<?php echo $this->url("admission",array("action"=>"rpt")); ?>">Reports</a></li>
                  </ul>
                </div>
            </nav>