<nav class="navbar navbar-submenu">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url("examination",array("action"=>"amgmt")); ?>">Assessments</a></li>
                    
                    <li><a href="#">My results</a></li>
                    <li><a href="<?php echo $this->url("examination",array("action"=>"rs")); ?>">Sign offs</a></li>
                    <li><a href="<?php echo $this->url("examination",array("action"=>"em")); ?>">Exam management</a></li>
                    <li><a href="<?php echo $this->url("examination",array("action"=>"ma")); ?>">Module allocations</a></li>
                    <li><a href="<?php echo $this->url("examination",array("action"=>"rpt")); ?>">Reports</a></li>
                  </ul>
                </div>
            </nav>