<nav class="navbar navbar-submenu">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="#"><a href="<?php echo $this->url("examination",array("action"=>"index")); ?>">Reports</a></li>
                    <li class="#"><a href="<?php echo $this->url("examination",array("action"=>"index")); ?>">Statement</a></li>
                   
                  </ul>
                </div>
            </nav>