<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MCA '. $this->translate('SIS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/plugins/fullcalendar/dist/fullcalendar.print.css'))
                        ->prependStylesheet($this->basePath('css/plugins/fullcalendar/dist/fullcalendar.css'))
                        ->prependStylesheet($this->basePath('css/plugins/dataTables.bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        
                       ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('http://code.highcharts.com/modules/exporting.js')
            ->prependFile('http://code.highcharts.com/highcharts.js')
            ->prependFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
            ->prependFile($this->basePath('js/plugins/jQuery-slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('js/custom.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
       
    </head>
    <body>
        <div class="container-fluid main-wrap">
        <div class="row header-wrap">
            <div class="col col-md-12">
                <div class="navbar-header"><img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="" class="img-responsive"></div>
                <ul class="nav navbar-nav navbar-right user-wrap">
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->identity()->getFirstname()." ".$this->identity()->getSurname(); ?> <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url("administration",array("action"=>"changepassword")); ?>">Change password</a></li>
                        
                        <li><a href="<?php echo $this->url("home",array("action"=>"logout")); ?>">Logout</a></li>
                      </ul>
                    </li>
                    <li><img src="<?php echo $this->basePath(); ?>/img/<?php echo ($this->identity()->getPhotoUrl() != null)?$this->identity()->getPhotoUrl():"placeholder.jpe"; ?>" alt="" height="50px" class=""></li>
                </ul>
            </div>  
        </div>
        <div class="row nav-wrap">
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="<?php echo ($this->activemodule=="home")?"active":""; ?>"><a href="#">Dashboard</a></li>
                    <li class="<?php echo ($this->activemodule=="admission")?"active":""; ?>"><a href="<?php echo $this->url("admission",array("action"=>"index")); ?>">Admission</a></li>
                    <li class="<?php echo ($this->activemodule=="examination")?"active":""; ?>"><a href="<?php echo $this->url("examination",array("action"=>"index")); ?>">Examination</a></li>
                    <li class="<?php echo ($this->activemodule=="finance")?"active":""; ?>"><a href="<?php echo $this->url("finance",array("action"=>"index")); ?>">Finance</a></li>
                    <li class="<?php echo ($this->activemodule=="accommodation")?"active":""; ?>"><a href="<?php echo $this->url("accommodation",array("action"=>"index")); ?>">Accommodation</a></li>
                    <li class="<?php echo ($this->activemodule=="administration")?"active":""; ?>"><a href="<?php echo $this->url("administration",array("action"=>"index")); ?>">Administration</a></li>
                  </ul>
                </div>
            </nav>              
        </div> 
        <div class="row">  
            <?php 
            echo $this->partial("application/submenu/{$this->activemodule}.phtml");
            echo $this->content; 
            ?>
        </div>
        <div class="row footer-wrap">
        <div class="col col-md-6">
            &copy; Copyright <?php echo date('Y'); ?> - Financial Data Portal. All rights reserved
        </div>
        <div class="col col-md-6 text-right">
            Powered by : <b>Code Dynamics</b>  :: SIS V.01
        </div>
    </div>        
        
    </div>
        
    </body>
</html>
