<?php echo $this->doctype(); ?>

<html lang="en" ng-app="app">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SARIS '. $this->translate(' v 2.0'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/plugins/fullcalendar/dist/fullcalendar.print.css'))
                        ->prependStylesheet($this->basePath('css/plugins/fullcalendar/dist/fullcalendar.css'))
                        ->prependStylesheet($this->basePath('css/plugins/dataTables.bootstrap.css'))
                        //->prependStylesheet($this->basePath('css/mtree.css'))
                        ->prependStylesheet($this->basePath('css/progress.css'))
                        ->prependStylesheet($this->basePath('css/edu/asset/css/AdminLTE.css'))
                        ->prependStylesheet($this->basePath('css/edu/asset/css/EdusecCustome.css'))
                        ->prependStylesheet($this->basePath('js/plugins/jquery-ui/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('css/plugins/fullcalendar/dist/fullcalendar.min.js'))
            ->prependFile($this->basePath('css/plugins/moment/min/moment.min.js'))
            ->prependFile($this->basePath('js/plugins/highchart/highcharts.js'))
            ->prependFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
           // ->prependFile($this->basePath('js/scroll/ngSlimscroll.js'))
            ->prependFile($this->basePath('js/plugins/ckeditor/ckeditor.js'))
            //->prependFile($this->basePath('js/jquery.form.js'))
            ->prependFile($this->basePath('js/custom.js'))
            ->prependFile($this->basePath('js/plugins/jquery-ui/jquery-ui.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            
                
           
        ; ?>
        <script type="text/javascript">
$(document).ready(function() {
  //Initializing calendar
    $('#calendar').fullCalendar({
        theme: false,
        events: 'http://localhost/smis/public/events'
    });
});
</script>
    </head>
    <body>
    <?php
    echo $this->partial('include/form/confirm.phtml');
    ?>
    <div class="container-fluid main-wrap">
        <div class="row header-wrap">
            <div class="col col-md-12">
                <div class="navbar-header "><img src="<?php echo $this->basePath(); ?>/img/logo.jpg" alt="" width="50" height="40" class="img-thumbnail"><span style="color:black; font-size:20px"> STUDENT INFORMATION SYSTEM(SARIS) </span></div>
                <?php
                if($this->identity()){
                ?>
                <ul class="nav navbar-nav navbar-right user-wrap">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span style="color:white;"><?php echo $this->identity()->getFirstname(); ?> <span class="caret"></span></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url("administration",array("action"=>"changepassword")); ?>">Change password</a></li>
                        <li><a href="<?php echo $this->url("home",array("action"=>"logout")); ?>">Logout</a></li>
                      </ul>
                    </li>
                    <li><img src="<?php echo $this->basePath(); ?>/img/placeholder.jpe" alt="" height="50px" class="img-circle"></li>
                </ul>
                <?php
                }
                ?>
            </div>  
        </div>
        <?php
        if($this->identity() && $this->activemodule != "login"){
            echo $this->partial("include/menu/main.phtml");
        }else{
            echo "<p />";
        }
        echo $this->content;
        ?>
        
    <div class="row footer-wrap">
        <div class="col col-md-6">
            &copy; Copyright <?php echo date('Y'); ?> - SARIS V. 02 .
</div>
</div>                
</div>
<?php echo $this->headScript()
            ->prependFile($this->basePath('js/mtree.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            
            
        ; ?>
<script type="text/javascript">
var app = angular.module('app', ['jkuri.slimscroll']);
</script>
       
</body>
</html>
