<div class="row">
        <div class="col col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            <h3 class="page-header">Finance</h3>
            <div class="panel-body">
            <div class="col text-right"><a class="btn btn-primary">Add New Item</a>  </div>
            <hr>
<table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
</table>
               
            </div>
                </div>
        </div>
</div>
        