<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-10 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Notice details</h4>
                    <div class="panel-body">
                       
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $title  = (!empty($details))?$details->getHeader():$form->get('Notice')->get('header')->getValue();
    $body    = (!empty($details))?$details->getBody():$form->get('Notice')->get('body')->getValue();
    $status  = (!empty($details))?$details->getIsActive():$form->get('Notice')->get('isActive')->getValue();
    $type   = (!empty($details))?$details->getAccountType():$form->get('Notice')->get('accountType')->getValue();
    $id     = (!empty($details))?$details->getPkNoticeid():$form->get('Notice')->get('pkNoticeid')->getValue();
 ?>
                            
    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Notice')->get('header')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Notice')->get('header')->setValue($title)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Notice')->get('header')); ?></div>
    </div>
  <?php echo $this->formFileSessionProgress(); ?>
    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Notice')->get('body')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Notice')->get('body')->setValue($body)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Notice')->get('body')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Notice')->get('accountType')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Notice')->get('accountType')->setValue($type)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Notice')->get('accountType')); ?></div>
    </div>
    
                        <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Notice')->get('isActive')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Notice')->get('isActive')->setValue($status)); ?>
           <?php echo $this->formHidden($form->get('Notice')->get('pkNoticeid')->setValue($id)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Notice')->get('isActive')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("communication",array("action"=>"index")); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
</div>
</div>
</div>
</div>
</div>
 <div>
        