
<div class="row">
    <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">
                    
                <h3 class="page-header"><?php echo $title; ?></h3>
                <hr>
    <div class="alert alert-danger">
        <i class="glyphicon glyphicon-warning-sign"></i> <?php echo $message; ?>
    </div>
                </div>
            </div>
    </div>
</div>
