
<div class="row">

        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Dashboard</h3>
            <div class="panel-body">
            
            <?php
            $x=1;
            if($x){
            ?>
            <div class="callout callout-info msg-of-day">
		    <h4><i class="glyphicon glyphicon-bullhorn"></i> Message of day box</h4>
		    <p>Each Day is a GIFT don't send it BACK unopened.  Have a nice Day !</p>
	</div>
            
            <?php
            }
            ?>
            <div class="row">
                <div class="col col-md-6">
                    <div class="row">
                        
                <div class="col col-md-12">
                    
                     
                    
                        <div class="box box-primary">
                            
                            
                            <div class="nav-tabs-custom"><!-- .nav-tabs-custom -->
                                <!-- Tabs within a box -->
                                <ul class="nav nav-tabs pull-right">
                                    <li><a href="#emp-notice" data-toggle="tab">Staff/Lecturer</a></li>
                                    <li><a href="#stu-notice" data-toggle="tab">Student</a></li>
				    <li class="active"><a href="#all-notice" data-toggle="tab">General</a></li>
                                    <li class="pull-left header" style=""><i class="glyphicon glyphicon-inbox"></i>Notice Board</li>
                                </ul>
                                <div class="tab-content">
                                    <!-- Notice -->
                                    <div class="tab-pane active" id="all-notice">
                                        <?php
                                        $numofitems = 5;
                                        $itemcount = 1;
                                        foreach($notices as $notice){
                                            if($itemcount > $numofitems){
                                                break;
                                            }
                                        ?>
					<div class="notice-main bg-light-blue">
						<div class="notice-disp-date">				        		<small class="label label-danger"><i class="glyphicon glyphicon-calendar"></i> <?php echo date_format($notice->getDatePublished(),"d M Y"); ?></small>	
						</div>
						<div class="notice-body">
                                                    <div class="notice-title"><a class="noticeModalLink" href="#" style="color:#FFF" data-value="/saris3/index.php?r=dashboard%2Fnotice%2Fview-popup&amp;id=3"><?php echo ucfirst(strtolower($notice->getHeader())); ?></a>&nbsp; </div>
                                                    <div class="notice-desc"><?php echo strip_tags($notice->getBody()); ?> </div>
						</div>					          
					</div>
                                        <?php
                                        
                                        $itemcount++;
                                        }
                                        ?>
				    </div>
                                    <div class="tab-pane" id="stu-notice">
					
										 <div class="notice-main bg-aqua">
						<div class="notice-disp-date">				        		<small class="label label-success"><i class="fa fa-calendar"></i> 01-06-2015</small>	
						</div>
						<div class="notice-body">
							 <div class="notice-title"><a class="noticeModalLink" href="#" style="color:#FFF" data-value="/saris3/index.php?r=dashboard%2Fnotice%2Fview-popup&amp;id=1">Next Week Summer Exam </a>&nbsp; </div>
							 <div class="notice-desc">summer Exam will be conducted on Next week. All The Best </div>
						</div>					          
					</div>
										 <div class="notice-main bg-aqua">
						<div class="notice-disp-date">				        		<small class="label label-success"><i class="fa fa-calendar"></i> 25-05-2015</small>	
						</div>
						<div class="notice-body">
							 <div class="notice-title"><a class="noticeModalLink" href="#" style="color:#FFF" data-value="/saris3/index.php?r=dashboard%2Fnotice%2Fview-popup&amp;id=5">Access to computer labs</a>&nbsp; </div>
							 <div class="notice-desc">All Students come and fill their exam forms </div>
						</div>					          
					</div>
									    </div>
				    <div class="tab-pane" id="emp-notice">
					
										 <div class="notice-main bg-teal">
						<div class="notice-disp-date">	<small class="label label-success"><i class="fa fa-calendar"></i> 05-06-2015</small>	
						</div>
						<div class="notice-body">
							 <div class="notice-title"><a class="noticeModalLink" href="#" style="color:#FFF" data-value="/saris3/index.php?r=dashboard%2Fnotice%2Fview-popup&amp;id=2">End of semester exam numbers </a>&nbsp; </div>
							 <div class="notice-desc">All Employee have to submit their report on month end. </div>
						</div>					          
					</div>
										 <div class="notice-main bg-teal">
						<div class="notice-disp-date">	<small class="label label-success"><i class="fa fa-calendar"></i> 29-05-2015</small>	
						</div>
						<div class="notice-body">
							 <div class="notice-title"><a class="noticeModalLink" href="#" style="color:#FFF" data-value="/saris3/index.php?r=dashboard%2Fnotice%2Fview-popup&amp;id=4">Attendance Report</a>&nbsp; </div>
							 <div class="notice-desc">All Employees collect their class wise  attendance report </div>
						</div>					          
					</div>
									    </div>
                                </div> <!--  /.tab-content -->
                            </div><!-- /.nav-tabs-custom -->
                    </div>
                </div>
                    </div>
                    <hr>
                    <div class="row">
                <div class="col col-md-12">
                  <div class="box box-warning">
		   <div class="box-header with-border">
			<h3 class="box-title "><i class="glyphicon glyphicon-calendar"></i> Calender of events</h3>
		   </div>
		   <div class="box-body">
                       <div id="calendar"></div>
                   </div>
                  </div>
                </div>
                    </div> 
                </div>
                <div class="col col-md-6">
                <div class="col col-md-12">
                   
                     
                       
                    
                    
                    
                    
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <div class="box box-danger">
		   <div class="box-header with-border">
			<h3 class="box-title "><i class="glyphicon glyphicon-warning-sign"></i> System alert</h3>
		   </div>
		   <div class="box-body">
		     <div class="table-responsive">
						<table class="table no-margin">
				<col class="col-sm-12">
				<tr>
					<th class="">Message</th>
				</tr>
				<tr>
                                    <td> <a href="<?php echo $this->url("admission",array("action"=>"srf")); ?>" class="text-danger">Registration period is set.</a></td>
				</tr>
                                <tr>
					<td> Examination numbers have been generated.</td>
				</tr>
                                <tr>
					<td> No academic session has been set.</td>
				</tr>
                                <tr>
					<td> Examination processing period set.</td>
				</tr>
								
							</table>
					     </div><!---/. end-responsive-div--->
		   </div><!---/. box-body--->
		</div><!---/. box--->
                        
                
                
                
                     </div>
                           
                        
                        </div>
                    </div>
                    
                    
                </div>
                </div>
            </div>
            
            

            </div>
                </div>
        </div>
    </div>