<div class="col col-md-10">
    <h3>Add user</h3>
    <hr>
    <div class="col col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>User information</strong></div>
            
            <div class="panel-body">
            <?php
            $userform->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off','id'=>'frmlogin'))->prepare();;
            echo $this->form()->openTag($userform);
            ?>
                <fieldset><legend>Personal information</legend>
                    <?php echo $this->formHidden($userform->get('User')->get('pkUserid')); ?>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('basicdetails')->get('surname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('basicdetails')->get('surname')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('User')->get('basicdetails')->get('surname')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('basicdetails')->get('firstname')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('basicdetails')->get('firstname')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('User')->get('basicdetails')->get('firstname')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('basicdetails')->get('initial')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('basicdetails')->get('initial')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php //echo $this->formElement($userform->get('User')->get('initial')); ?>
                       </div>
                      
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($userform->get('User')->get('basicdetails')->get('gender')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($userform->get('User')->get('basicdetails')->get('gender')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    
                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($userform->get('User')->get('basicdetails')->get('emailaddress')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($userform->get('User')->get('basicdetails')->get('emailaddress')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('User')->get('basicdetails')->get('emailaddress')); ?></div>
                    </div>
                </fieldset>
                <fieldset><legend>Login information</legend>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('username')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('username')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('User')->get('username')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('password')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('password')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('User')->get('password')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('User')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('User')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php //echo $this->formElement($userform->get('User')->get('initial')); ?>
                       </div>
                      
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-3"><?php echo $this->formLabel($userform->get('User')->get('fkRoleid')); ?></div>
                       <div class="col-sm-5">
                            <?php echo $this->formElement($userform->get('User')->get('fkRoleid')); ?>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>
                    
                    
                </fieldset>
                
                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Save Data" />
                           <input name="cancel" type="submit" class="btn btn-warning" value="Cancel" />
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
        