<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header"> <?php echo $session->getAcyr(); ?>Event details</h4>
                    <div class="panel-body">
                       
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $type   = (!empty($details))?$details->getFkEventtypeid()->getPkEventtypeid():$form->get('Event')->get('fkEventtypeid')->getValue();
    $start  = (!empty($details))?$details->getStart():$form->get('Event')->get('start')->getValue();
    $end    = (!empty($details))?$details->getEnd():$form->get('Event')->get('end')->getValue();
    $group  = (!empty($details))?$details->getTargetgroup():$form->get('Event')->get('targetgroup')->getValue();
    $id     = (!empty($details))?$details->getPkEventid():$form->get('Event')->get('pkEventid')->getValue();
    
 ?>
                            
    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Event')->get('fkEventtypeid')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Event')->get('fkEventtypeid')->setValue($type)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Event')->get('fkEventtypeid')); ?></div>
    </div>
  <?php //echo $this->formFileSessionProgress(); ?>
    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Event')->get('start')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Event')->get('start')->setValue($start)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Event')->get('start')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Event')->get('end')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Event')->get('end')->setValue($end)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Event')->get('end')); ?></div>
    </div>
    
                        <div class="form-group">   
       <div class="col-sm-2"><?php echo $this->formLabel($form->get('Event')->get('targetgroup')); ?> </div>
       <div class="col-sm-7">
           <?php echo $this->formElement($form->get('Event')->get('targetgroup')->setValue($group)); ?>
           <?php echo $this->formHidden($form->get('Event')->get('pkEventid')->setValue($id)); ?>
       </div>
       <div class="col-sm-3"><?php echo $this->formElementErrors($form->get('Event')->get('targetgroup')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-2"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("administration",array("action"=>"asc","id"=>$session->getPkAcademicperiodid())); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
</div>
</div>
</div>
</div>
</div>
 <div>
        