<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Change password</h4>
                    <div class="panel-body">
            <?php
            $form->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off'))->prepare();
            echo $this->form()->openTag($form);
            ?>
                
                
                    <?php echo $this->formHidden($form->get('Password')->get('pkUserid')->setValue($userid)); ?>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($form->get('oldpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($form->get('oldpassword')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('oldpassword')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($form->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($form->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Password')->get('password')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($form->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($form->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php echo $this->formElementErrors($form->get('Password')->get('cpassword')); ?>
                       </div>
                      
                    </div>

                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Change" />
                           <a href="<?php echo $this->url("home",array("action"=>"index")); ?>"  class="btn btn-warning">Cancel</a>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
</div>
        