<?php
echo $this->partial('include/form/modalform.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
     $("a[title='modify']").click(function(){
        $("input[name='groupCode']").val($("#code"+this.id).html());
        $("input[name='groupName']").val($("#name"+this.id).html());
        $("input[name='level']").val($("#level"+this.id).html());
        $("input[name='pkGroupid']").val($("#id"+this.id).val());
    });

      //Assig a foreign key to modal window
    $('#formmodal').on('shown.bs.modal', function () {
        $("input[name='fkProgramid']").val($("#fk").val());
    });
});
</script>
<div class="col col-md-10">
    <h3><?php if(!$moduleallocation){ echo $program->getProgName(); ?> classes/courses <?php }else{ ?>Module allocation <?php } ?></h3>
    <hr>
    <?php if(!$moduleallocation){ ?>
    <div class="row">
    <div class="col col-md-4">
        
        

    </div>

    <div class="col col-md-8 text-right">
        <a data-toggle="modal" data-target="#formmodal" class="btn btn-primary">Allocate</a>&nbsp;&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"programs")); ?>" class="btn btn-primary">Programs</a>  
    </div>
</div>
    
    <hr>
    <?php
    }
    ?>
    <table class="table table-bordered table-hover" id="searchable">
        <thead>
            <tr>
                
                <th>Code</th>
                <th>Name</th>
                <th>Level/Year</th>
                <th width="60"></th>
            </tr>
        </thead>
        <tbody>
        <?php
        if(!empty($classes)){
        $counter = 1;
        foreach($classes as $class){
        ?>
        <tr>
            <td id="code<?php echo $counter; ?>"><?php echo $class->getGroupCode(); ?></td>
            <input value="<?php echo $class->getPkGroupid(); ?>" id="id<?php echo $counter; ?>" type="hidden" />
            <td id="name<?php echo $counter; ?>"><?php echo $class->getGroupName(); ?></td>
            <td id="level<?php echo $counter; ?>"><?php echo $class->getLevel(); ?></td>
            <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <?php if(!$moduleallocation){ ?>
                        <li role="presentation">
                            <a title="modify" id="<?php echo $counter; ?>" data-toggle="modal" data-target="#formmodal" style="cursor: pointer" >Modify</a>
                        </li>
                        <?php
                        }else{
                        ?>
                        <li role="presentation">
                            <a id="<?php echo $counter; ?>" href="<?php echo $this->url("administration",array("action"=>"classmodules","id"=>$class->getPkGroupid())); ?>"  style="cursor: pointer" >Allocate modules</a>
                        </li>
                        <?php
                        }
                        ?>
                                              
                    </ul>
                </div></td>
        </tr>
        <?php
        $counter++;
        }
        }
        ?>
        </tbody>
    </table>
    <div class="col">
        <?php if(!$moduleallocation){ ?>
        <input id="fk" value="<?php echo $program->getPkProgramid(); ?>" type="hidden" />
        <?php
        }
        ?>
    <form class="form-inline" role="form">
        
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
    </form>    
    </div>
</div>
        