<div class="row">

        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Modules</h3>
            <div class="panel-body">
                
                <h4><?php echo $class->getClassName()."(".$class->getClassCode().")"; ?></h4>
                <hr>
                
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"classmoduleform","id"=>$class->getPkClassid())); ?>" class="btn btn-primary">Add New</a>&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$class->getFkProgramid()->getFkdeptid()->getPkDeptid())); ?>" class="btn btn-warning">Back</a>  </div>
            <hr>
             <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success alert-dismissible"><?php echo $msg; ?></div>
            <?php
            }
            ?>
            <table class="table table-bordered table-striped table-hover" id="searchable">
    <thead>
      <tr>
        <th>Module</th>
        <th>Semester</th>
        <th>Exam Weight(%)</th>
        <th>CWK Weight(%)</th>
        
        <th>Is core</th>
        <th>Is project</th>
        <th width="80"></th>
      </tr>
    </thead>
    <tbody>
      
      <?php
      foreach($modules as $module){
      ?>
      <tr>
        <td><?php echo $module->getFkModuleid()->getModuleName()."( ".$module->getFkModuleid()->getModuleCode().")"; ?></td>
        <td><?php echo $module->getFkAcademicperiod()->getAcyr(); ?></td>
        <td><?php echo $module->getExweight(); ?></td>
        <td><?php echo $module->getCwkweight(); ?></td>
        
        <td><?php echo ($module->getIsCore()==1)?"Yes":"No"; ?></td>
        <td><?php echo ($module->getIsProject()==1)?"Yes":"No"; ?></td>
        <td>
            <a href="<?php echo $this->url("administration",array("action"=>"classmoduleform","id"=>$class->getPkClassid(),"subid"=>$module->getPkClassmoduleid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            
            <a href="<?php //echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
           </td>
      </tr>
       <?php
      }
      ?>
    </tbody>
</table>
                
            </div>
                </div>
        </div>
</div>
        