<div class="row">
<div class="col col-md-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="POST" action="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$department->getPkDeptid())); ?>">
                    <div class="form-group"><select name="programid" class="form-control" placeholder="Search program" >
                    <?php
                    foreach($programs as $program){
                    ?>
                        <option value="<?php echo $program->getPkProgramid(); ?>"><?php echo $program->getProgramCode(); ?></option>
                    <?php
                    }
                    ?>
                    </select><br>
                    <button class="btn btn-success"><i class="glyphicon glyphicon-search"></i> View</button>
                </div>
                </form>
            </div>
        </div>
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
            <h3 class="page-header">Programs</h3>
            <div class="panel-body">
                
                <h4><?php echo $department->getDeptName()."(".$department->getDeptCode().")"; ?></h4>
                <hr>
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"programform","id"=>$department->getPkDeptid())); ?>" class="btn btn-primary">Add New</a>&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"departments","id"=>$department->getFkFacultyid()->getPkFacultyid(),"subid"=>$department->getPkDeptid())); ?>" class="btn btn-warning">Back</a>  </div>
            <hr>
            
             <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success alert-dismissible"><?php echo $msg; ?></div>
            <?php
            }
            if(count($initialprogram)==1){
            ?>
            
            
           
            
            <div class="alert alert-info"><div class="pull-right"><a title="Assign courses to classes" href="<?php echo $this->url("administration",array("action"=>"classmoduleview","id"=>$department->getPkDeptid(),"subid"=>$initialprogram->getPkProgramid())); ?>" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-asterisk"></i></a><a href="<?php echo $this->url("administration",array("action"=>"programform","id"=>$department->getPkDeptid(),"subid"=>$initialprogram->getPkProgramid())); ?>" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-edit"></i></a><button class="btn btn-sm btn-default"><i class="glyphicon glyphicon-remove"></i></button></div><div><strong><?php echo $initialprogram->getProgramLongName(); ?>(<?php echo $initialprogram->getProgramCode(); ?>)<br><?php echo $initialprogram->getDuration(); ?> Years<br><?php echo $initialprogram->getFkAwardid()->getAward(); ?></strong></div></div>
            <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"programclassform","id"=>$initialprogram->getPkProgramid())); ?>" class="btn btn-primary">Add class</a>&nbsp;  </div><br>
            <table class="table table-bordered table-striped table-hover" id="searchable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Mode</th>
        <th>Year</th>
        <th width="130"></th>
      </tr>
    </thead>
    <tbody>
      
      <?php
      foreach($classes as $class){
      ?>
      <tr>
        <td><?php echo $class->getClassName(); ?></td>
        <td><?php echo $class->getClassCode(); ?></td>
        <td><?php echo $class->getFkTmodeid()->getTitle(); ?></td>
        <td><?php echo $class->getClassYear(); ?></td>
       
        <td>
            <a href="<?php echo $this->url("administration",array("action"=>"programclassform","id"=>$initialprogram->getPkProgramid(),"subid"=>$class->getPkClassid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?php echo $this->url("administration",array("action"=>"classmodules","id"=>$class->getPkClassid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-list"></i></a>
            <a href="<?php //echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
        </td>
      </tr>
       <?php
       }
       }
      ?>
    </tbody>
</table>
                
            </div>
                </div>
        </div>
</div>
        