<div class="row">

        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Departments</h3>
            <div class="panel-body">
                
                <h4><?php echo $faculty->getFacultyName()."(".$faculty->getFacultyCode().")"; ?></h4>
                <hr>
                
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"departmentform","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-primary">Add New</a>&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"faculties")); ?>" class="btn btn-warning">Back</a>  </div>
            <hr>
             <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success alert-dismissible"><?php echo $msg; ?></div>
            <?php
            }
            ?>
            <table class="table table-bordered table-striped table-hover" id="searchable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Head</th>
        <th width="150"></th>
      </tr>
    </thead>
    <tbody>
      
      <?php
      foreach($departments as $department){
      ?>
      <tr>
        <td><?php echo $department->getDeptName(); ?></td>
        <td><?php echo $department->getDeptCode(); ?></td>
        <td><?php echo (!empty($department->getFkStaffid()))?$department->getFkStaffid()->getFkUserid()->getFirstname()." ".$department->getFkStaffid()->getFkUserid()->getSurname():"Not assigned"; ?></td>
        <td>
            <a href="<?php echo $this->url("administration",array("action"=>"departmentform","id"=>$faculty->getPkFacultyid(),"subid"=>$department->getPkDeptid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$department->getPkDeptid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-list"></i></a>
            <a href="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$department->getPkDeptid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-list-alt"></i></a>
            <a href="<?php //echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
        </td>
      </tr>
       <?php
      }
      ?>
    </tbody>
</table>
                
            </div>
                </div>
        </div>
</div>
        