<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Department details</h4>
                    <div class="panel-body">
                        <div class="alert alert-info"><strong><?php echo $faculty->getFacultyName()."(".$faculty->getFacultyCode().")"; ?></strong></div>
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $name    = (!empty($details))?$details->getDeptName():$form->get('Department')->get('deptName')->getValue();
    $code    = (!empty($details))?$details->getDeptCode():$form->get('Department')->get('deptCode')->getValue();
    $user    = (!empty($details))?$details->getFkStaffid():$form->get('Department')->get('fkStaffid')->getValue();
   // $faculty = (!empty($details))?$details->getFkFacultyid():$form->get('Department')->get('fkFacultyid')->getValue();
    $id      = (!empty($details))?$details->getPkDeptid():$form->get('Department')->get('pkDeptid')->getValue();
 ?>
                            
    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Department')->get('deptName')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Department')->get('deptName')->setValue($name)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Department')->get('deptName')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Department')->get('deptCode')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Department')->get('deptCode')->setValue($code)); ?>
           <?php echo $this->formHidden($form->get('Department')->get('pkDeptid')->setValue($id)); ?>
            <?php echo $this->formHidden($form->get('Department')->get('fkFacultyid')->setValue($faculty->getPkFacultyid())); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Department')->get('deptCode')); ?></div>
    </div>
    <?php
    if($id){
    ?>
    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Department')->get('fkStaffid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Department')->get('fkStaffid')->setValue($user)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Department')->get('fkStaffid')); ?></div>
    </div>
    <?php
    }
    ?>

    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>