<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Faculty details</h4>
                    <div class="panel-body">
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $name = (!empty($details))?$details->getFacultyName():$form->get('Faculty')->get('facultyName')->getValue();
    $code = (!empty($details))?$details->getFacultyCode():$form->get('Faculty')->get('facultyCode')->getValue();
    $user = (!empty($details))?$details->getFkStaffid():$form->get('Faculty')->get('fkStaffid')->getValue();
    $id   = (!empty($details))?$details->getPkFacultyid():$form->get('Faculty')->get('pkFacultyid')->getValue();
 ?>
                            
    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Faculty')->get('facultyName')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Faculty')->get('facultyName')->setValue($name)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Faculty')->get('facultyName')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Faculty')->get('facultyCode')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Faculty')->get('facultyCode')->setValue($code)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Faculty')->get('facultyCode')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Faculty')->get('fkStaffid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Faculty')->get('fkStaffid')->setValue($user)); ?>
           <?php echo $this->formHidden($form->get('Faculty')->get('pkFacultyid')->setValue($id)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Faculty')->get('fkStaffid')); ?></div>
    </div>
                            

    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("administration",array("action"=>"faculties")); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>