<div class="row">

        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Faculties</h3>
            <div class="panel-body">
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"facultyform")); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-plus"></i> Add New</a>  </div>
            <hr>
            <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <?php echo $msg; ?>
            </div>
            <?php
            }
            ?>
            <table class="table table-bordered table-striped table-hover" id="searchable">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Dean</th>
        <th width="110"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($faculties as $faculty){
      ?>

      <tr>
        <td><?php echo $faculty->getFacultyCode()?></td>
        <td><?php echo $faculty->getFacultyName()?></td>
        <td><?php echo (!empty($faculty->getFkStaffid()))?$faculty->getFkStaffid()->getFkUserid()->getFirstname()." ".$faculty->getFkStaffid()->getFkUserid()->getSurname():"Not assigned"; ?></td>
        <td><a href="<?php echo $this->url("administration",array("action"=>"facultyform","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?php echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-list"></i></a>
            <a href="<?php //echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
        </td>
      </tr>
      <?php
      }
      ?>
    </tbody>
</table>
                
            </div>
                </div>
        </div>
</div>
        