<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Manage users/groups</h3>
            <div class="panel-body">
            
            <hr>
            
            <div class="row">
                <div class="col-md-6">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Users</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/user.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                                Select this task to upload a new selection list to the system.
                                <p></p>
                                <a href="<?php echo $this->url("administration",array("action"=>"users")); ?>" class="btn btn-sm btn-info">View list</a>
                                
                            </div>
                        </div>    
                    </div>
                    
                </div>
                <div class="col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Groups/roles</div>
                        <div class="panel-body">
                             <div class="col col-md-3"><img src="<?php echo $this->basePath(); ?>/img/group.png" width="90" alt="" class="img-thumbnail" /></div>
                            <div class="col col-md-9">
                                Selected students ought to be assigned registration numbers.
                                <p></p>
                                <a href="<?php echo $this->url("administration",array("action"=>"users")); ?>" class="btn btn-sm btn-info">View list</a>
                                
                            </div>
                        </div> 
                    </div>
                </div>
               
            </div>

            </div>
                </div>
        </div>
    </div>