<?php
echo $this->partial('include/form/modalform.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
//     $("a[title='modify']").click(function(){
//        $("input[name='deptCode']").val($("#deptcode"+this.id).html());
//        $("input[name='deptName']").val($("#deptname"+this.id).html());
//        $("input[name='pkDepartmentid']").val($("#deptid"+this.id).val());
//    });

      //Assig a foreign key to modal window
    $('#formmodal').on('shown.bs.modal', function () {
        $("input[name='fkDeptid']").val($("#fk").val());
    });
});
</script>
<div class="col col-md-10">
    <h3>Lecturers - <?php echo $department->getDeptName(); ?></h3>
    <hr>
    <div class="row">
    <div class="col col-md-4">
        
        

    </div>

    <div class="col col-md-8 text-right">
        <a data-toggle="modal" data-target="#formmodal" class="btn btn-primary">Allocate</a>&nbsp;&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"departments")); ?>" class="btn btn-primary">Departments</a>  
    </div>
</div>
    
    <hr>
    <table class="table table-bordered table-hover" id="searchable">
        <thead>
            <tr>
                
                <th>Last name</th>
                <th>First name</th>
                <th>Gender</th>
                <th>Mode</th>
                <th>Email address</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if(!empty($users)){
        foreach($users as $user){
        ?>
        <tr>
            <td><?php echo $user->getFkUserid()->getSurname(); ?></td>
            <td><?php echo $user->getFkUserid()->getFirstname(); ?></td>
            <td><?php echo $user->getFkUserid()->getGender(); ?></td>
            <td><?php echo $user->getMode(); ?></td>
            <td><?php echo $user->getFkUserid()->getEmailaddress(); ?></td>
        </tr>
        <?php
        }
        }
        ?>
        </tbody>
    </table>
    <div class="col">
        <input id="fk" value="<?php echo $department->getPkDepartmentid(); ?>" type="hidden" />
    <form class="form-inline" role="form">
        
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
    </form>    
    </div>
</div>
        