<?php
echo $this->partial('include/form/modalform.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
      $("a[title='modify']").click(function(){
        $("input[name='moduleCode']").val($("#code"+this.id).html());
        $("input[name='moduleName']").val($("#name"+this.id).html());
        $("input[name='pkModuleid']").val($("#id"+this.id).val());
    });
});
</script>
<div class="col col-md-10">
    <h3>Modules</h3>
    <hr>
    <div class="row">
    <div class="col col-md-4">
        
        

    </div>

    <div class="col col-md-8 text-right">
        <a data-toggle="modal" data-target="#formmodal" class="btn btn-primary">Add module</a>
    </div>
</div>
    
    <hr>
    <table class="table table-bordered table-hover" id="searchable">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th width="60"></th>
                
            </tr>
        </thead>
        <tbody>
        <?php
        $counter = 1;
        foreach($modules as $module){
        ?>
        <tr>
            <td><span id="code<?php echo $counter; ?>"><?php echo $module->getModuleCode(); ?></span></td>
            <td id="name<?php echo $counter; ?>"><?php echo $module->getModuleName(); ?></td>
            <input value="<?php echo $module->getPkModuleid(); ?>" id="id<?php echo $counter; ?>" type="hidden" />
            <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <li role="presentation">
                            <a title="modify" id="<?php echo $counter; ?>" data-toggle="modal" data-target="#formmodal" style="cursor: pointer" >Modify</a>
                        </li>
                        <li role="presentation">
                            <a  href="<?php echo $this->url("administration",array("action"=>"modulefees","id"=>$module->getPkModuleid())); ?>">Fees</a>
                        </li>                        
                    </ul>
                </div>    </td>
            
        </tr>
        <?php
            $counter++;
        }
        ?>
        </tbody>
    </table>
    <div class="col ">
    <form class="form-inline" role="form">
        
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
    </form>    
    </div>
</div>
        