<div class="row">
        <div class="col col-md-12">
            <div class="col col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h4 class="page-header">Class details</h4>
                    <div class="panel-body">
                        <div class="alert alert-info"><strong><?php echo $program->getProgramName()."(".$program->getProgramCode().")"; ?></strong></div>
<?php
    
    $form->setAttributes(array('name'=>'formsubmit','class'=>'form-horizontal'))->prepare();
    echo $this->form()->openTag($form);
    $name    = (!empty($details))?$details->getClassName():$form->get('Class')->get('className')->getValue();
    $code    = (!empty($details))?$details->getClassCode():$form->get('Class')->get('classCode')->getValue();
    $year    = (!empty($details))?$details->getClassYear():$form->get('Class')->get('classYear')->getValue();
    $mode    = (!empty($details))?$details->getFkTmodeid()->getPkStudymodeid():$form->get('Class')->get('fkTmodeid')->getValue();
    $id      = (!empty($details))?$details->getPkClassid():$form->get('Class')->get('pkClassid')->getValue();
 ?>                    
   <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Class')->get('className')); ?> </div>
       <div class="col-sm-5">
            <?php echo $this->formElement($form->get('Class')->get('className')->setValue($name)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Class')->get('className')); ?></div>
    </div>

    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Class')->get('classCode')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Class')->get('classCode')->setValue($code)); ?>
           <?php echo $this->formHidden($form->get('Class')->get('pkClassid')->setValue($id)); ?>
            <?php echo $this->formHidden($form->get('Class')->get('fkProgramid')->setValue($program->getPkProgramid())); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Class')->get('classCode')); ?></div>
    </div>
   <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Class')->get('classYear')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Class')->get('classYear')->setValue($year)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Class')->get('classYear')); ?></div>
    </div>
    <div class="form-group">   
       <div class="col-sm-3"><?php echo $this->formLabel($form->get('Class')->get('fkTmodeid')); ?> </div>
       <div class="col-sm-5">
           <?php echo $this->formElement($form->get('Class')->get('fkTmodeid')->setValue($mode)); ?>
       </div>
       <div class="col-sm-4"><?php echo $this->formElementErrors($form->get('Class')->get('fkTmodeid')); ?></div>
    </div>
    <div class="form-group">   
       <div class="col-sm-3"></div>
       <div class="col-sm-5">
           <input type="submit" name="save" class="btn btn-success" value="Save" />
           <a href="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$program->getFkDeptid()->getPkDeptid())); ?>" class="btn btn-warning">Cancel</a>
       </div>
       <div class="col-sm-4"></div>
    </div>                            
<?php
 echo $this->form()->closeTag();
?>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>