<div class="row">

        <div class="col col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            <h3 class="page-header">System preferences</h3>
            <div class="panel-body">
 
                <blockquote class="panel-primary text-info">Audit</blockquote>
                <div class="row">
                    <div class="col-md-1"></div><div class="col-md-4"><h4><span class="text-danger">Password length:</span> 10 Characters</h4></div>
                </div>
                <div class="row">
                    <div class="col-md-1"></div><div class="col-md-4"><h4><span class="text-danger">Password expiry days:</span> 10</h4></div>
                </div>
                <div class="row">
                    <div class="col-md-1"></div><div class="col-md-4"><h4><span class="text-danger">Log file:</span> C:\log\log20140204.txt</h4></div>
                </div> 
                <blockquote class="panel-primary text-info">Grades flow</blockquote>
                <div class="col-md-1"></div><div class="col-md-2"><div class="alert alert-info">Lecturer</div></div>
                <div class="col-md-2"><div class="alert alert-info">Head</div></div>
                <div class="col-md-2"><div class="alert alert-info">Dean</div></div>
                <div class="col-md-2"><div class="alert alert-info">Registrar</div></div>
                <div class="col-md-2"><div class="alert alert-info">College</div></div>
            </div>
                </div>
        </div>
</div>
        