<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header"><?php echo $academicyear->getAcyr(); ?> Semesters</h3>
            <div class="panel-body">
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"semesterform","id"=>$academicyear->getPkAcademicperiodid())); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-plus"></i> Add New</a>&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"academicperiod")); ?>" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-backward"></i> Return</a>  </div>
            <hr>
            <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <?php echo $msg; ?>
            </div>
            <?php
            }
            ?>
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Semester</th>
        <th>Start date</th>
        <th>End date</th>
        <th width="100"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($periods as $period){
      ?>

      <tr>
        <td><?php echo $period->getAcyr(); ?></td>
        <td><?php echo date_format($period->getStartDate(),"d M Y"); ?></td>
        <td><?php echo date_format($period->getEndDate(),"d M Y"); ?></td>
        <td>
            <a href="<?php echo $this->url("administration",array("action"=>"semesterform","id"=>$academicyear->getPkAcademicperiodid(),"subid"=>$period->getPkAcademicperiodid())); ?>" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?php //echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>  </td>
      </tr>
      <?php
      }
      ?>
    </tbody>
</table>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
</div>
        