<div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="panel panel-default">
            <h3 class="page-header">Users</h3>
            <div class="panel-body">
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"userform")); ?>" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-plus"></i> Add New</a> <a href="<?php echo $this->url("administration",array("action"=>"index")); ?>" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-backward"></i> Return</a>  </div>
            <hr>
            <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <?php echo $msg; ?>
            </div>
            <?php
            }
            ?>
            <table class="table table-bordered table-striped table-hover" id="searchable">
    <thead>
      <tr>
        <th>Username</th>
        <th>Title</th>
        <th>First name</th>
        <th>Surname</th>
        <th>Gender</th>
        <th>Role/group</th>
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($users as $user){
      ?>

      <tr>
        <td><?php echo $user->getUsername(); ?></td>
        <td><?php echo $user->getTitle(); ?></td>
        <td><?php echo $user->getFirstname(); ?></td>
        <td><?php echo $user->getSurname(); ?></td>
        <td><?php echo $user->getGender(); ?></td>
        <td><?php echo $user->getFkRoleid()->getDescription(); ?></td>
        <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <li role="presentation">
                            <a title="modify" id="<?php //echo $counter; ?>" href="<?php echo $this->url("administration",array("action"=>"userform","id"=>$user->getPkUserid())); ?>"  ><i class="glyphicon glyphicon-edit"></i> Edit</a>
                        </li>
                        <li role="presentation">
                            <a  href="<?php //echo $this->url("administration",array("action"=>"lecturers","id"=>$department->getPkDepartmentid())); ?>"><i class="glyphicon glyphicon-remove"></i> Delete</a>
                        </li> 
                        <li role="presentation">
                            <a  href="<?php echo $this->url("administration",array("action"=>"userdetails","id"=>$user->getPkUserid())); ?>"><i class="glyphicon glyphicon-list"></i> Details</a>
                        </li> 
                    </ul>
                </div>    </td>
      </tr>
      <?php
      }
      ?>
    </tbody>
</table>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
</div>
        